readme, contribution, pylint
meri-nova/discord pull request #5
Opened 2024-02-12 08:13 UTC by thebadcoder96

Wowow this bot is building up quickly! :) 

Here are the PR details:

- Updated `readme.md` file to add more information about the bot and its features.
- Added `CONTRIBUTING.md` with guidelines on how to contribute. I have added a section on how to set up the discord running for development. I know @MAdhavbhatia222 has some notes on it and this should be his next PR :)
- Added Linting with `pylint`. Added pylint to our workflow in GitHub Actions as well. Linting will help us write better and more clean code.

@meri-nova I ran pylint and our score was **4.69** but I did some basic best practices like removing trail spaces and breaking down lines of code and our score is now **7.19**. To increase our score, we should add stuff like docstring our functions (add proper comments/documentation). This will also make our code base more readable and set it to a good standard. Anyone who is interested in contributing to start can try to do this and make our code base better :)
>Once this is merged, I can create an issue highlighting this and we can add people to just comment on the issue if they want to work on it.

2024-02-12 09:03 UTC, KostyaCholak commented on src/discord_app.py
> +DISCORD_SERVER_ID = os.getenv('DISCORD_SERVER_ID') or '0'
I guess this line should already be different. @meri-nova didn't we change it to get the values using `os.environ[...]`? I don't think that a default value of zero is a good idea, we should enforce the existence of this env variable by making the program fail with key error, or by explicitly raising an exception explaining that this setting is required.

2024-02-12 09:04 UTC, KostyaCholak commented
Thanks for your contribution!!! I'm excited to see people working on this

2024-02-12 09:10 UTC, thebadcoder96 commented on src/discord_app.py
> +DISCORD_SERVER_ID = os.getenv('DISCORD_SERVER_ID') or '0'
oh totally. I was just messing around trying to get GitHub actions pytest to run. But it seems like the pytest we are using is trying to get these variables from `${{ secrets.DISCORD_SERVER_ID }}`. I think we should rather be mocking these things using pytest mock. I am looking into it.

2024-02-12 18:16 UTC, KostyaCholak commented on requirements.txt
> +#below are for testing
Let's put development reqs into a different requirements file (requirements-dev.txt for example).

2024-02-12 18:19 UTC, KostyaCholak commented
It would be faster to review and iterate if we split each feature/fix/chore into a separate PR. Then it would be possible to merge what we agree on and discuss the other blocked PRs

2024-02-12 23:17 UTC, thebadcoder96 commented on requirements.txt
> +#below are for testing
I love the idea of a separate dev and test requirements file.

2024-02-12 23:19 UTC, thebadcoder96 commented
> It would be faster to review and iterate if we split each feature/fix/chore into a separate PR. Then it would be possible to merge what we agree on and discuss the other blocked PRs

You are right. My intent last night was to only work on the docs but one redbull in I got a little carried away and started doing all this in the same branch. I will stop here and once the god of this repo @meri-nova has blessed us with comments and successful merges, I will create separate PRs for each issue/feature/fix

2024-02-13 01:01 UTC, meri-nova requested changes
Hi. Can you delete changes in test_bot.py.

2024-02-13 01:05 UTC, thebadcoder96 commented on src/test_bot.py
Roger that

2024-02-13 01:09 UTC, meri-nova approved these changes
Great job!!!!

2024-02-13 01:12 UTC, merged